In [1]:
#Import Library 
import pandas as pd

In [ ]:
#Load the dataset
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\datasets\transactions_merchant_master.csv")

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used,merchant_name,category,city,country,onboarding_date,commission_rate,rating,active_status
0,1,80,2,2024-06-05,923.09,Card,Success,12,18.46,True,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
1,2,11,6,2024-03-02,801.29,Apple Pay,Success,3,16.03,True,Merchant6,Restaurant,Abu Dhabi,UAE,2025-03-22,1.07,3.6,True
2,3,89,20,2024-04-30,1231.47,Google Pay,Success,3,24.63,False,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True
3,4,90,15,2024-01-19,2123.80,Apple Pay,Failed,12,42.48,True,Merchant15,Electronics,Riyadh,Saudi Arabia,2024-08-10,2.14,4.0,True
4,5,70,8,2024-06-14,1281.17,Apple Pay,Failed,3,25.62,True,Merchant8,Restaurant,Dubai,UAE,2025-02-02,3.20,3.7,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,52,20,2024-06-16,2792.75,Google Pay,Success,3,55.86,False,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True
496,497,26,17,2024-03-14,1322.53,Apple Pay,Success,12,26.45,True,Merchant17,Restaurant,Abu Dhabi,UAE,2023-03-17,3.31,4.4,True
497,498,87,2,2024-04-02,1849.42,Apple Pay,Success,3,36.99,True,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
498,499,100,13,2024-03-31,2990.48,Wallet,Failed,12,59.81,True,Merchant13,Electronics,Dubai,UAE,2024-12-26,3.14,3.5,True
499,500,95,3,2024-01-24,1558.05,Google Pay,Failed,6,31.16,False,Merchant3,Restaurant,Jeddah,Saudi Arabia,2023-08-06,2.42,3.5,True

In [ ]:
#Displays the dataframe
df

In [4]:
#Average Transaction Amount
df["amount"].mean()

np.float64(1493.1972800000003)

In [14]:
#Median Transaction Amount
#The median is the middle value after sorting the data
df["amount"].median()

np.float64(1457.435)

In [ ]:
#Mode Transaction Amount
df["amount"].mode()

0        18.19
1        21.41
2        24.09
3        24.45
4        30.42
        ...
495    2977.12
496    2978.61
497    2987.95
498    2990.48
499    2999.93
Name: amount, Length: 500, dtype: float64

In [ ]:
#Minimum Transaction Amount
df["amount"].min()

np.float64(18.19)

In [ ]:
#Maximum Transaction Amount
df["amount"].max()

np.float64(2999.93)

In [11]:
#Range 
range = df["amount"].max() - df["amount"].min()
range

np.float64(2981.74)

In [ ]:
#Variance of Transaction Amount
df["amount"].var()

np.float64(705582.5571769555)

In [ ]:
#Standard deviation of Transaction Amount
#Lower standard deviation - customers spread similar amounts 
#Higher standard deviation - customer spending varies considerably 
df["amount"].std()

np.float64(839.9896173030685)

In [16]:
#First Quartile (25%)
df["amount"].quantile(0.25)

np.float64(808.29)

In [18]:
#Median (50%)
df["amount"].quantile(0.50)

np.float64(1457.435)

In [20]:
#Third Quartile (75%)
df["amount"].quantile(0.75)

np.float64(2240.7625)

In [22]:
#90th percentile
df["amount"].quantile(0.90)

np.float64(2636.2010000000005)

In [23]:
#95th percentile
df["amount"].quantile(0.95)

np.float64(2839.4685)

Correlation

In [24]:
#Does cashback increase as transaction amoount increases?
df[["amount","cashback"]].corr()

          amount  cashback
amount       1.0       1.0
cashback     1.0       1.0

Interpretation:
- +1 -> Perfect positive relationship
- 0 -> No relationship
- -1 -> Perfect negative relationship

Outlier Detection

In [31]:
#Are there any unusually large transactions that require investigation?
Q1 = df["amount"].quantile(0.25)
Q1

np.float64(808.29)

In [32]:
Q3 = df["amount"].quantile(0.75)
Q3

np.float64(2240.7625)

In [ ]:
#Interquartile Range
IQR =Q3 - Q1
IQR

np.float64(1432.4724999999999)

In [ ]:
#Finding lower and upper bound
lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

In [35]:
lower

np.float64(-1340.4187499999998)

In [36]:
upper

np.float64(4389.47125)

In [ ]:
#Finding outliers
outliers = df[(df["amount"]<lower)|(df["amount"]>upper)]
outliers

Empty DataFrame
Columns: [transaction_id, customer_id, merchant_id, transaction_date, amount, payment_method, transaction_status, installment_months, cashback, wallet_used, merchant_name, category, city, country, onboarding_date, commission_rate, rating, active_status]
Index: []

There seems to be no outliers according to the IQR method.

In [ ]:
#checking if there are any outliers
len(outliers)

0

In [ ]:
#Checking the shape of the outlier
outliers.shape

(0, 18)

Business Insight:
- No statistical outliers were detected in transaction amounts using the IQR method
- Customer spending falls within the expected range of the dataset
- There are no unusually high or unusually low transactions requiring further investigation

Business Actions:
- Continue monitoring transaction amount as new data is collected 
- Apply the same outlier detection process regularly to identify unusual spending patterns or potential fradulent transactions