In [21]:
#Import pandas 
import pandas as pd

In [22]:
#Load the merged of transaction and merchant dataset
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\datasets\transactions_merchant_master.csv")
df

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used,merchant_name,category,city,country,onboarding_date,commission_rate,rating,active_status
0,1,80,2,2024-06-05,923.09,Card,Success,12,18.46,True,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
1,2,11,6,2024-03-02,801.29,Apple Pay,Success,3,16.03,True,Merchant6,Restaurant,Abu Dhabi,UAE,2025-03-22,1.07,3.6,True
2,3,89,20,2024-04-30,1231.47,Google Pay,Success,3,24.63,False,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True
3,4,90,15,2024-01-19,2123.80,Apple Pay,Failed,12,42.48,True,Merchant15,Electronics,Riyadh,Saudi Arabia,2024-08-10,2.14,4.0,True
4,5,70,8,2024-06-14,1281.17,Apple Pay,Failed,3,25.62,True,Merchant8,Restaurant,Dubai,UAE,2025-02-02,3.20,3.7,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,52,20,2024-06-16,2792.75,Google Pay,Success,3,55.86,False,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True
496,497,26,17,2024-03-14,1322.53,Apple Pay,Success,12,26.45,True,Merchant17,Restaurant,Abu Dhabi,UAE,2023-03-17,3.31,4.4,True
497,498,87,2,2024-04-02,1849.42,Apple Pay,Success,3,36.99,True,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
498,499,100,13,2024-03-31,2990.48,Wallet,Failed,12,59.81,True,Merchant13,Electronics,Dubai,UAE,2024-12-26,3.14,3.5,True
499,500,95,3,2024-01-24,1558.05,Google Pay,Failed,6,31.16,False,Merchant3,Restaurant,Jeddah,Saudi Arabia,2023-08-06,2.42,3.5,True

Executive KPI's

In [24]:
#Total Revenue
total_revenue = df["amount"].sum().round(2)
print("Total Revenue:", total_revenue)

Total Revenue: 746598.64

In [25]:
#Total transactions
total_transactions = df["transaction_id"].count()
print("Total Transactions:",total_transactions)

Total Transactions: 500

In [27]:
#Average transaction value
average_transaction = df["amount"].mean().round(2)
print("Average Transaction:",average_transaction)

Average Transaction: 1493.2

In [29]:
#Highest Transaction 
highest_transaction = df["amount"].max()
print("Highest Transaction:",highest_transaction)

Highest Transaction: 2999.93

In [31]:
#Lowest Transaction 
lowest_transaction = df["amount"].min()
print("Lowest Transaction:",lowest_transaction)

Lowest Transaction: 18.19

In [34]:
#Total cashback 
total_cashback = df["cashback"].sum()
print("Total Cashback:", total_cashback)

Total Cashback: 14931.98

In [37]:
#Average Cashback
average_cashback = df["cashback"].mean().round(2)
print("Average Cashback:",average_cashback)

Average Cashback: 29.86

In [38]:
#Number of merchants 
number_of_merchants = df["merchant_id"].nunique()
print("Number of Merchants:",number_of_merchants)

Number of Merchants: 20

In [42]:
#Number of Merchant categories 
merchant_categories = df["category"].nunique()
print("Number of Merchant Categories:",merchant_categories)

Number of Merchant Categories: 4

In [44]:
#Number of Payment Method
payment_methods = df["payment_method"].nunique()
print("Number of Payment Methods:",payment_methods)

Number of Payment Methods: 4

In [55]:
#Transaction success rate
successful_transactions = df["transaction_status"]=="Success"
total_transactions = len(df["transaction_status"])
success_rate = (successful_transactions.sum()/total_transactions)*100
print("Success Rate:",success_rate,"%")

Success Rate: 50.2 %

In [58]:
#Failed transaction rate 
failed_transaction = df["transaction_status"]=="Failed"
total_transactions = len(df["transaction_status"])
failed_rate = (failed_transaction.sum()/total_transactions)*100
print("Failed Rate:",failed_rate,"%")

Failed Rate: 49.8 %

In [73]:
#Pivot tables 1 - Revenue by Merchant Category 
pd.pivot_table(df,values="amount",index="category",aggfunc="sum")

                amount
category
Electronics  186793.81
Grocery      161022.62
Restaurant   220859.30
Travel       177922.91

In [64]:
#Revenue by Payment Method 
pd.pivot_table(df,values="amount",index="payment_method",aggfunc="sum")

                   amount
payment_method
Apple Pay       176250.72
Card            161435.34
Google Pay      229172.58
Wallet          179740.00

In [65]:
#Transaction Count by Merchant Category
pd.pivot_table(df,values="transaction_id",index="category",aggfunc="count")

             transaction_id
category
Electronics             115
Grocery                 105
Restaurant              157
Travel                  123

In [66]:
#Average transaction Value
pd.pivot_table(df,values="amount",index="category",aggfunc="mean")

                  amount
category
Electronics  1624.294000
Grocery      1533.548762
Restaurant   1406.747134
Travel       1446.527724

In [68]:
#Cashback by Merchant Category
pd.pivot_table(df,values="cashback",index="category",aggfunc="sum")

             cashback
category
Electronics   3735.88
Grocery       3220.44
Restaurant    4417.21
Travel        3558.45

In [69]:
#Revenue by Merchant x Payment Method 
pd.pivot_table(df,values="amount",index="category",columns="payment_method",aggfunc="sum")

payment_method  Apple Pay      Card  Google Pay    Wallet
category
Electronics      43303.76  24779.00    62706.91  56004.14
Grocery          34335.81  48057.28    53183.66  25445.87
Restaurant       63867.53  49720.55    56985.09  50286.13
Travel           34743.62  38878.51    56296.92  48003.86

In [ ]:
#Transaction status by payment method
pd.pivot_table(df,values="transaction_id",index="payment_method",columns="transaction_status",aggfunc="count",fill_value=0)

transaction_status  Failed  Success
payment_method
Apple Pay               64       53
Card                    57       55
Google Pay              66       86
Wallet                  62       57

In [72]:
#Merchant Performance dashboard
pd.pivot_table(df,values="amount",index="merchant_name",aggfunc=["sum","mean","count"])

                    sum         mean  count
                 amount       amount amount
merchant_name
Merchant1      25004.47  1389.137222     18
Merchant10     42069.30  1314.665625     32
Merchant11     34549.59  1439.566250     24
Merchant12     32188.56  1788.253333     18
Merchant13     36384.63  1581.940435     23
Merchant14     32441.27  1707.435263     19
Merchant15     43959.26  1569.973571     28
Merchant16     49256.89  1759.174643     28
Merchant17     36696.60  1668.027273     22
Merchant18     45140.36  1612.155714     28
Merchant19     40281.21  1299.393871     31
Merchant2      50432.04  1576.001250     32
Merchant20     45043.19  1324.799706     34
Merchant3      42115.41  1403.847000     30
Merchant4      35496.33  1419.853200     25
Merchant5      40467.96  1618.718400     25
Merchant6      35287.18  1534.225217     23
Merchant7      29072.50  1615.138889     18
Merchant8      21248.96   923.867826     23
Merchant9      29462.93  1550.680526     19