In [170]:
#Import pandas and numpy 
import pandas as pd
import numpy as np

In [171]:
#Load the dataset
df=pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\datasets\transactions.csv")

In [172]:
#Displays the dataframe
df

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used
0,1,80,2,2024-06-05,923.09,Card,Success,12,18.46,True
1,2,11,6,2024-03-02,801.29,Apple Pay,Success,3,16.03,True
2,3,89,20,2024-04-30,1231.47,Google Pay,Success,3,24.63,False
3,4,90,15,2024-01-19,2123.80,Apple Pay,Failed,12,42.48,True
4,5,70,8,2024-06-14,1281.17,Apple Pay,Failed,3,25.62,True
...,...,...,...,...,...,...,...,...,...,...
495,496,52,20,2024-06-16,2792.75,Google Pay,Success,3,55.86,False
496,497,26,17,2024-03-14,1322.53,Apple Pay,Success,12,26.45,True
497,498,87,2,2024-04-02,1849.42,Apple Pay,Success,3,36.99,True
498,499,100,13,2024-03-31,2990.48,Wallet,Failed,12,59.81,True
499,500,95,3,2024-01-24,1558.05,Google Pay,Failed,6,31.16,False

In [ ]:
#Convert to Numpy Arrays
amount = df["amount"].to_numpy()
cashback = df["cashback"].to_numpy()
installments = df["installment_months"].to_numpy()
payment = df["payment_method"].to_numpy()
status = df["transaction_status"].to_numpy()
wallet = df["wallet_used"].to_numpy()
merchant = df["merchant_id"].to_numpy()
customer = df["customer_id"].to_numpy()

Finance Analytics

In [174]:
#How many transactions are there?
len(amount)

500

In [175]:
#What is the total transaction value?
np.sum(amount).round(2)

np.float64(746598.64)

In [176]:
#What is the average transaction amount?
np.mean(amount).round(2)

np.float64(1493.2)

In [177]:
#What is median transaction amount?
np.median(amount).round(2)

np.float64(1457.44)

In [178]:
#What is the highest transaction amount?
np.max(amount)

np.float64(2999.93)

In [179]:
#What is the lowest transaction amount?
np.min(amount)

np.float64(18.19)

In [180]:
#What is the transaction range?
transaction_range = np.max(amount) - np.min(amount)
transaction_range

np.float64(2981.74)

In [181]:
#What is the standard deviation of the transaction amounts?
np.std(amount)

np.float64(839.1492072704362)

In [182]:
#What are the 25th,50th,75th transaction percentiles?
np.percentile(amount,[25,50,75])

array([ 808.29  , 1457.435 , 2240.7625])

In [183]:
#What is the total cashback paid?
np.sum(cashback)

np.float64(14931.98)

Payment Analytics

In [184]:
#Which payment method are available?
np.unique(payment)

array(['Apple Pay', 'Card', 'Google Pay', 'Wallet'], dtype=object)

In [185]:
#How many transactions were made using each payment method?
methods,counts = np.unique(payment,return_counts=True)

for method,count in zip(methods,counts):
    print(method,count)

Apple Pay 117
Card 112
Google Pay 152
Wallet 119

In [186]:
#Which payment method is the most popular?
methods[np.argmax(counts)]

'Google Pay'

In [187]:
#Which payment method is the least popular?
methods[np.argmin(count)]

'Apple Pay'

In [188]:
#What percentage of transactions used each payment method?
percentages = (counts/len(payment))*100
percentages

for method,pct in zip(methods,percentages):
    print(method,round(pct,2))

Apple Pay 23.4
Card 22.4
Google Pay 30.4
Wallet 23.8

Operations Analytics

In [189]:
df

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used
0,1,80,2,2024-06-05,923.09,Card,Success,12,18.46,True
1,2,11,6,2024-03-02,801.29,Apple Pay,Success,3,16.03,True
2,3,89,20,2024-04-30,1231.47,Google Pay,Success,3,24.63,False
3,4,90,15,2024-01-19,2123.80,Apple Pay,Failed,12,42.48,True
4,5,70,8,2024-06-14,1281.17,Apple Pay,Failed,3,25.62,True
...,...,...,...,...,...,...,...,...,...,...
495,496,52,20,2024-06-16,2792.75,Google Pay,Success,3,55.86,False
496,497,26,17,2024-03-14,1322.53,Apple Pay,Success,12,26.45,True
497,498,87,2,2024-04-02,1849.42,Apple Pay,Success,3,36.99,True
498,499,100,13,2024-03-31,2990.48,Wallet,Failed,12,59.81,True
499,500,95,3,2024-01-24,1558.05,Google Pay,Failed,6,31.16,False

In [194]:
#What transaction statuses exist?
np.unique(status)

array(['Failed', 'Success'], dtype=object)

In [192]:
#How many transactions are in each status?
statuses,counts = np.unique(status,return_counts=True)

for s,c in zip(statuses,counts):
    print(s,c)

Failed 249
Success 251

In [195]:
#which status is most common?
status[np.argmax(counts)]

'Success'

In [201]:
#How many successful transactions are there?
np.sum(status=="Success")

np.int64(251)

In [205]:
#What percentage of all transactions were successful?
(np.sum(status=="Success")/len(status))*100

np.float64(50.2)

Cashback Analytics

In [206]:
#Average Cashback
np.mean(cashback)

np.float64(29.86396)

In [208]:
#Highest Cashback
np.max(cashback)

np.float64(60.0)

In [209]:
#Lowest Cashback
np.min(cashback)

np.float64(0.36)

In [210]:
#Total Cashback
np.sum(cashback)

np.float64(14931.98)

In [212]:
#Customers receiving above average cashback
customer[cashback>np.mean(cashback)]

array([ 90,  90,  95,  74,  57,  37,  37,  40,  32,  36,  75,  70,  30,
        57,  43,  31,  21,  59,  33,  60,  39,  79,  30,  23,  31,  14,
        53,  12,  72,  93,  55,  52,  73,  35,  76,   8,  30,  29,  45,
        65,  11,  68,  19,  20,  80,  99,  31,  54,  71,  54,   3,  64,
        47,  48,  81,  83,   9,  41,  25,  56,  48,  24,  40,  87,  51,
        64,  58,  71,  66,  17,  75,  81,  66,  60,  31,  94,  25,  36,
         6,  65,  85,  44,  51,  90,  68,  99,  23,   2,  70,  43,  73,
        86,  57,  59,  87,   6,  49,  51,  38,  85,  76,  86,   8,  97,
        49,  64,  63,  53,  37,  31,  84,  13,  76,  50,  45,  79,  58,
        85,  64,  71,  53,  49,  47,  58,  43,  69,  45,  41,  66,  15,
        57,  31,  27,  36,  98,  17,  59,  55,  93,  55,  14,  97,  22,
        12,  89,  38,  77,   2,  65,  93,  16,  22,  32,  49,  19,  48,
        51,  18,  48,   7,  62,  30,  29,  95,  25,  26,  44,  63,  99,
        14,  22,  13,   5,  56,  73,  53,  88,  22,  56,   2,  34,   7,
        42,  53,  26,  36, 100, 100,  77,  31,  84,  75,  86,  49,  44,
        63,  82,  32,   3,  80, 100,  13,  87,  94,  78,  47,  47,  51,
         1,  23,  18,  89,  69,  87,   7,  70,  10,  20,  67,  66,  55,
        72,  83,  70,   2,  51,  40,  43,  23,  28,  67,  42,  46,  28,
        77,  77,  70,  55,  41,  53,  58,  52,  87, 100,  95])

In [213]:
#Top 10% cashback threshold
np.percentile(cashback,90)

np.float64(52.726000000000006)

Installment Analytics

In [215]:
#Average installment period
np.mean(installments)

np.float64(6.996)

In [216]:
#Highest installmet period
np.max(installments)

np.int64(12)

In [217]:
#Lowest installment period
np.min(installments)

np.int64(3)

In [224]:
#How many transactions were made without installments?
np.sum(installments==0)

np.int64(0)

In [226]:
#How many transactions have installments greater than 6 months?
np.sum(installments>6)

np.int64(170)

Wallet Usage Analytics

In [228]:
#How many transactions used the wallet?
np.sum(wallet)

np.int64(266)

In [230]:
#How many did not use the wallet?
np.sum(~wallet)

np.int64(234)

In [231]:
#What percentage of transactions used in the wallet?
(np.sum(wallet)/len(wallet))*100

np.float64(53.2)

In [232]:
#What is the average transaction amount for wallet users?
np.mean(amount[wallet])

np.float64(1549.331992481203)

In [233]:
#What are the average transaction amount for non-wallet users?
np.mean(amount[~wallet])

np.float64(1429.3860256410255)